<span style="font-family:Comic Sans MS; color:red">1. Pandas - loc:
Given the following DataFrame `df`, write a command to select all rows where the value in the 'Age'
column is greater than 30 using `loc`</span> 

In [1]:
import pandas as pd

data = {'Name': ['John', 'Anna', 'Peter', 'Linda'],
 'Age': [28, 34, 29, 40],
 'City': ['New York', 'Paris', 'Berlin', 'London']}
df = pd.DataFrame(data)

agegreaterthan30 = df.loc[df['Age'] > 30]
agegreaterthan30

Name  Age      City
0   John   28  New York
1   Anna   34     Paris
2  Peter   29    Berlin
3  Linda   40    London

<span style="font-family:Comic Sans MS; color:red">2. Pandas - loc:
Using `loc`, how would you select the 'Name' and 'City' columns for rows where the 'Age' column is
less than or equal to 29 in the given DataFrame `df`?</span>

In [8]:
ageLessthanOrEqualTo29 = df.loc[df['Age'] <= 29, ['Name', 'City']]
ageLessthanOrEqualTo29

Name      City
0   John  New York
2  Peter    Berlin

<span style="font-family:Comic Sans MS; color:red">3. Pandas - iloc:
Given the same DataFrame `df`, write a command to select the first two rows using `iloc`.</span>

In [11]:
FirstRow = df.iloc[:1]
FirstRow

Name  Age      City
0  John   28  New York

<span style="font-family:Comic Sans MS; color:red">4. Pandas - iloc:
Using `iloc`, how would you select the 'Name' and 'City' columns for the last two rows of the
DataFrame `df`?</span>

In [21]:
Last2Rows = df.iloc[-2:,[0,2]]
Last2Rows

Name    City
2  Peter  Berlin
3  Linda  London

<span style="font-family:Comic Sans MS; color:red">5. Pandas - loc & iloc:
Explain the difference between `loc` and `iloc` in pandas. Provide an example using the DataFrame
`df`.</span>

In [27]:
Last2RowsUsingIloc = df.iloc[-2:,[0,2]]
Last2RowsUsingloc = df.loc[2:,('Name','City')]
print(f"Using Loc = {Last2RowsUsingloc}\nUsing ILoc = {Last2RowsUsingIloc}")

Using Loc =     Name    City
2  Peter  Berlin
3  Linda  London
Using ILoc =     Name    City
2  Peter  Berlin
3  Linda  London


<span style="font-family:Comic Sans MS; color:red">6. Pandas - loc:
Using the DataFrame `df`, write a command to set the 'City' column to 'Unknown' for all rows where
the 'Age' is greater than 30 using `loc`.</span>

In [45]:
setUnknown = df
setUnknown.loc[setUnknown['Age'] > 30, "City"] = "unknown"
setUnknown

Name  Age      City
0   John   28  New York
1   Anna   34   unknown
2  Peter   29    Berlin
3  Linda   40   unknown

<span style="font-family:Comic Sans MS; color:red">7. Pandas - iloc:
Using `iloc`, how would you select the second and third rows and the 'Name' and 'City' columns of
the DataFrame `df`?</span>

In [41]:
SecondandThirdRows = df.iloc[2:4,[0,2]]
SecondandThirdRows

Name     City
2  Peter   Berlin
3  Linda  unknown

<span style="font-family:Comic Sans MS; color:red">8. Pandas - loc:
Given the DataFrame `df`, write a command to select all columns for rows where 'City' is 'Paris'
using `loc`.</span>

In [52]:
data = {'Name': ['John', 'Anna', 'Peter', 'Linda'],
 'Age': [28, 34, 29, 40],
 'City': ['New York', 'Paris', 'Berlin', 'London']}
df = pd.DataFrame(data)
ParisData = df.loc[df['City'] == "Paris"]
ParisData

Name  Age   City
1  Anna   34  Paris

<span style="font-family:Comic Sans MS; color:red">9. Pandas - iloc:
Using `iloc`, how would you select every other row and all columns from the DataFrame `df` starting
from the first row?</span>

In [53]:
df.iloc[::2]

Name  Age      City
0   John   28  New York
2  Peter   29    Berlin

<span style="font-family:Comic Sans MS; color:red">10. Pandas - loc:
Using `loc`, write a command to select all rows where 'Name' starts with the letter 'P' in the
DataFrame `df`.</span>

In [56]:
startp = df.loc[df['Name'].str.startswith('P')]
startp

Name  Age    City
2  Peter   29  Berlin

<span style="font-family:Comic Sans MS; color:red">11. Numpy - Creating Array:
Write a command to create a 1D numpy array with values ranging from 0 to 9.</span>

In [59]:
import numpy as np

N = np.arange(0,10)
N

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<span style="font-family:Comic Sans MS; color:red">12. Numpy - Random:
Using numpy, generate a 2D array of shape (3, 3) with random integer values between 10 and 50.</span>

In [67]:
N = np.random.randint(10,50,9)
N.reshape(3,3)

array([[19, 12, 36],
       [42, 15, 31],
       [46, 16, 10]])

<span style="font-family:Comic Sans MS; color:red">13. Numpy - Linspace:
Write a command to create a numpy array with 5 evenly spaced values between 0 and 1.</span>

In [69]:
N = np.linspace(0,1,5)
N

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

<span style="font-family:Comic Sans MS; color:red">14. Numpy - Arange:
Using numpy, create an array with values starting from 10 to 100 with a step size of 10.</span>

In [71]:
N = np.arange(10,100,10)
N

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

<span style="font-family:Comic Sans MS; color:red">15. Numpy - Multidimensional Array:
Convert the 1D numpy array `[1, 2, 3, 4, 5, 6]` into a 2x3 2D array and slice the array to get the first
row</span>

In [74]:
N = [1, 2, 3, 4, 5, 6]
N = np.array(N)
N.reshape(2,3)[0]


array([1, 2, 3])